=== CORM/Cassandra-Orm/bin/com/corm/xsd/orm-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/SAP-ORM-CONFIGURATION" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/SAP-ORM-CONFIGURATION">
    <element name="orm-configuration">
	    <complexType>
	    	<sequence>
    		<element name="session-factory"
    			type="tns:session-factory" maxOccurs="1" minOccurs="1">
    		</element>
    		</sequence>
	    </complexType>
    </element>
    
    <complexType name="session-factory">
    	<sequence>
    		<element name="property" type="tns:property" minOccurs="1" maxOccurs="unbounded"></element>
			<element name="mapping" type="tns:mapping" minOccurs="1" maxOccurs="unbounded"></element>
			<element name="strategy" type="tns:strategy" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>  
    	<attribute name="scan-path" type="string" use="required"></attribute>
    </complexType>


    <complexType name="property">
    	<attribute name="name" type="string" use="required"></attribute> 
    	<attribute name="value" type="string" use="required"></attribute>
    </complexType>
    <complexType name="mapping">
    	<attribute name="resource" type="string" use="required"></attribute> 
    </complexType>
    
    <complexType name="strategy">
    	<sequence>
    		<element name="action" type="tns:action" minOccurs="1" maxOccurs="1"></element>
    	</sequence>  
    	<attribute name="mode" type="string" use="required"></attribute>
    	<attribute name="attributeType" type="string" use="required"></attribute> 
    </complexType>
 
	<complexType name="action">
	    	<sequence>
    		<element name="value"
    			type="string" maxOccurs="1" minOccurs="1">
    		</element>
    		</sequence>
	 </complexType>
</schema>

=== CORM/Cassandra-Orm/src/com/corm/hbm/mapping/orm-configuration.xml
<?xml version="1.0" encoding="utf-8"?>
<orm-configuration xmlns="http://www.example.org/CASSANDRA-ORM-CONFIGURATION" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/CASSANDRA-ORM-CONFIGURATION orm-configuration.xsd ">
	<session-factory scan-path="com.foo.model.*,com.foo1.generator.goals.*, com.foo3.util.*">
	 	<property name="orm.connection.driver_class" value="" />
		<property name="orm.connection.url" value="jdbc:sap://LLBPAL03.pal.sap.corp:30015"/>
		<property name="orm.connection.username" value="RDSUSER"/>
		<property name="orm.connection.password" value="Welcome2"/>
		<property name="show_sql" value="true"/>
		<strategy attributeType="java.sql.Timestamp" mode="db">
      		<action>
        		<value>SELECT ${hint} FROM DUMMY</value>
      		</action>
    	</strategy>
		<strategy attributeType="java.lang.Integer" mode="db">
      		<action>
        		<value>SELECT ${hint} FROM DUMMY</value>
      		</action>
    	</strategy>
	</session-factory>
</orm-configuration>
